import {ICompetence} from './types';

export const references = [
  {
    title: 'RubiKube',
    year: 2022,
    description:
      "RubiKube is the best place to learn and improve at rubik's cube.",
    skills: ['TypeScript', 'React', 'Next.js', 'ThreeJS'],
    url: 'https://rubikube.vercel.app/',
  },
  {
    title: 'Password cracker',
    year: 2022,
    description: 'Provide a hashed password and the hash method, and then the program will retrieve the password in clear.',
    skills: ['Bash', 'OpenSSL'],
    url: 'https://www.github.com/leoroullois/password_cracker',
  },
  {
    title: 'Basic Shell',
    year: 2022,
    description: 'A basic shell created in C.',
    skills: ['C'],
    url: 'https://www.github.com/leoroullois/basic-shell',
  },
];

export const competences: ICompetence[] = [
  {
    category: 'Web',
    label: 'HTML & CSS',
    logo: '/skills/html_css.png',
    width: 1280 / 30,
    height: 829 / 30,
  },
  {
    category: 'Web',
    label: 'JavaScript',
    logo: '/skills/javascript.svg',
    width: 35,
    height: 35,
  },
  {
    category: 'Web',
    label: 'TypeScript',
    logo: '/skills/typescript.svg',
    width: 35,
    height: 35,
  },
  {
    category: 'Web',
    label: 'React',
    logo: '/skills/react.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Redux',
    logo: '/skills/redux.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'SASS',
    logo: '/skills/sass.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Tailwind',
    logo: '/skills/tailwind_css.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Next.js',
    logo: '/skills/nextjs.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Node.js',
    logo: '/skills/nodejs.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Express',
    logo: '/skills/express-js.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Web',
    label: 'Strapi',
    logo: '/skills/strapi.svg',
    //TODO: link
    width: 40,
    height: 40,
  },
  {
    category: 'API & Database',
    label: 'RESTful',
    logo: '/skills/api.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'API & Database',
    label: 'GraphQL',
    logo: '/skills/graphql.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'API & Database',
    label: 'MongoDB',
    logo: '/skills/mongodb.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'API & Database',
    label: 'PostgreSQL',
    logo: '/skills/pgsql.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Tools & other',
    label: 'Docker',
    logo: '/skills/docker.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Tools & other',
    label: 'Git',
    logo: '/skills/git.png',
    width: 40,
    height: 40,
  },
  {
    category: 'Tools & other',
    label: 'GitHub',
    logo: '/skills/github.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Tools & other',
    label: 'C',
    logo: '/skills/c.svg',
    width: 40,
    height: 40,
  },
  {
    category: 'Tools & other',
    label: 'Linux',
    logo: '/skills/linux.svg',
    width: 40,
    height: 40,
  },
];
